"""Updated User model

Revision ID: 034e30cde5f3
Revises: 6fd95ad5e7df
Create Date: 2024-11-10 18:03:05.227477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034e30cde5f3'
down_revision = '6fd95ad5e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
